version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-lts
    ports:
      - "8085:8080"
      - "50005:50000"
    volumes:
      - local-jenkins-lts-volume:/var/jenkins_home
    dns:
      - 1.1.1.1
      - 8.8.8.8
    ulimits:
      nofile:
        soft: 8096
        hard: 8096
volumes:
  local-jenkins-lts-volume:
    external: true
